version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:20"
      timezone: Asia/Taipei
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    groups:
      production-dependencies:
        dependency-type: production
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
      development-major:
        dependency-type: development
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:20"
      timezone: Asia/Taipei
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
